Add text editor
tokitou-san/CoreProject-V3-UI pull request #274
Opened 2023-06-12 16:04 UTC by baseplate-admin

There could be minor styling issues. Take a look

2023-06-12 16:14 UTC, tokitou-san requested changes
Good work!
Here are some bugs :)

Line breaking is not working properly on preview tab

[Screencast from 2023-06-12 21-40-02.webm](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/c91a4526-e5c0-4f10-89ea-b3dbb2c2a4e4)

2023-06-12 16:17 UTC, baseplate-admin commented
tracking : https://github.com/markedjs/marked/issues/190

2023-06-13 01:29 UTC, baseplate-admin commented on src/lib/components/shared/markdown.svelte
> +    export let markdown: string;
Dont change it. Marked throws error with empty string

2023-06-13 01:29 UTC, baseplate-admin commented on src/lib/components/shared/text_editor.svelte
> +    let textarea_value: string;
Dont change it. Marked throws error with empty string

2023-06-13 01:29 UTC, baseplate-admin commented on src/lib/components/shared/markdown.svelte
> +        breaks: true,
What is the point?

2023-06-13 02:01 UTC, baseplate-admin commented on src/lib/components/shared/text_editor.svelte
> +            </button>
Switch to better DS

2023-06-13 14:11 UTC, merged