style: make info page responsive
tokitou-san/CoreProject-V3-UI pull request #281
Opened 2023-06-14 10:36 UTC by tokitou-san

**In progress...............................................................................................................................................................................**

2023-06-14 10:38 UTC, baseplate-admin requested changes
Change it please

2023-06-14 10:38 UTC, baseplate-admin commented on src/lib/components/pages/anime_info/anime_episodes.svelte
> +                        {/each}
```svelte
  {#each ["1080p", "720p", "480p"] as resolution}
                            <span class="flex h-full place-items-center rounded bg-surface-400 px-2 leading-[0.9vw] md:rounded-[0.25vw] md:px-[0.9vw]">
                                {resolution}
                            </span>
                        {/each}
```

2023-06-14 12:40 UTC, baseplate-admin commented on src/lib/components/pages/anime_info/anime_episodes.svelte
>          {/each}
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/43ff4a2a-3db6-4055-8a2d-d2b0c0b9c280)

This is how it's supposed to look like

2023-06-14 12:47 UTC, baseplate-admin commented on src/lib/components/pages/anime_info/anime_episodes.svelte
>          {/each}
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/b60f2cf5-5b4b-4aac-99a2-5c79057c528d)

2023-06-14 13:17 UTC, baseplate-admin commented on src/lib/components/pages/anime_info/anime_episodes.svelte
>          {/each}
Can you spot the difference ?

2023-06-14 13:28 UTC, tokitou-san commented on src/lib/components/pages/anime_info/anime_episodes.svelte
>          {/each}
> This is how it's supposed to look like

Oky image not rendered that time.

Yea I see, do we need a toggle button to change between these two layouts? or just keep that?

2023-06-16 08:20 UTC, baseplate-admin commented
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/7f896b6b-7306-480e-a218-45900aab7427)

hey i have found a regression

2023-06-16 08:21 UTC, baseplate-admin commented
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/c9711379-1061-4a9b-95cd-b796eb062b67)


Notice how the ui becomes transparent ?

2023-06-16 14:27 UTC, merged

2023-06-16 14:27 UTC, tokitou-san commented
I want fishhhh

2023-06-16 14:28 UTC, baseplate-admin commented
🗿