fix: 404 page background gradient
tokitou-san/CoreProject-V3-UI pull request #415
Opened 2023-07-11 16:52 UTC by tokitou-san

2023-07-14 01:08 UTC, baseplate-admin commented on src/lib/components/pages/anime_info/error.svelte
> +    style="background-image: linear-gradient(to top left, rgba(117, 105, 225, 0.1) 0%, transparent 50%);"
Make it center?

2023-07-14 01:40 UTC, baseplate-admin commented
@tokitou-san, LMK if this makes better sense :)

2023-07-14 17:20 UTC, tokitou-san commented
![Screenshot from 2023-07-14 22-42-32](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/c6c74ed7-252a-4341-8bf5-16a0bcbfdbc5)

Looks good in mobile?
and it seems like `40vw` is the only perfect value for both.... but isnt it looks small in mobile?

It looks really good in desktop :P
what about add a gradient from bottom like I did before for mobile only?
gradient has height issues with mobile....

![Screenshot from 2023-07-14 22-48-54](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/1a88134d-93a3-4ad0-9c3a-6c1722db4453)

See? Lemme see if there is any other fix for this :P

2023-07-15 04:43 UTC, baseplate-admin commented
Fixed

2023-07-15 04:51 UTC, tokitou-san commented
![Screenshot from 2023-07-15 10-18-21](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/1309da43-a5fd-48a9-aa00-dc6bc97ede3a)

It still has height issue, see?
needa move gradient element outside character element
or adjust height of image gradient

You on this?

2023-07-15 05:02 UTC, baseplate-admin commented
fixed

2023-07-15 05:40 UTC, baseplate-admin requested changes

2023-07-15 05:40 UTC, baseplate-admin commented on src/lib/components/pages/anime_info/error.svelte
> +            {#each Array.from("404") as number}
Not a big fan

2023-07-15 06:16 UTC, tokitou-san commented
@baseplate-admin Now its ready to merge...

2023-07-15 06:16 UTC, merged